#!/usr/bin/env python3

import os
import argparse
import subprocess as sp

def get_inputs():
	parser = argparse.ArgumentParser()
	parser.add_argument("inputs", help="input configurations in the form 'a 1, b 2, ...'")
	args = parser.parse_args()
	inputs = args.inputs.strip()
	return [p.split() for p in inputs.split(",")]
	
def run_command(command):
	proc = sp.Popen(command, shell=True, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE)
	out, err = proc.communicate()
	return out.decode('utf-8'), err.decode('utf-8')

def main():
	abspath = os.path.abspath(os.path.expanduser(__file__))
	dirname = os.path.dirname(abspath)
	exepath = os.path.join(dirname, "exec")

	inputs = get_inputs()
	varnames, varvals = zip(*inputs)
	command = '{} {}'.format(exepath, ' '.join(varvals))

	out, err = run_command(command)
	assert not err, "command {} failed: {}".format(command, err)
	print(','.join(out.split()))

if __name__ == '__main__':
	main()
